### PR TITLE
feat: translate admin app

### PR DESCRIPTION
**Pull request by gempain**
Placeholder PR until I finish working.

---

Before submitting this PR, I have:
- [x] read the [contributing guidelines](https://github.com/medusajs/medusa/blob/develop/CONTRIBUTING.md#merge-style)
- [x] [searched for existing issues or created a new one](https://github.com/medusajs/medusa/blob/develop/CONTRIBUTING.md#issues-before-prs)
- [x] [reached out](https://github.com/medusajs/medusa/blob/develop/CONTRIBUTING.md#important) to [CODEOWNERS](https://github.com/medusajs/medusa/blob/develop/CODEOWNERS)

Related PRs:
- https://github.com/medusajs/medusa/pull/4190 (thanks to @mj-mehdizadeh for his work)

Related issues:
- https://github.com/medusajs/medusa/issues/2055
- https://github.com/medusajs/medusa/discussions/2003

**What**

This PR adds translations to the Medusa Admin dashboard:
- auto detection of language
- storage in `localStorage`

**Why**

- Not everyone using Medusa actually speaks English
- Vendure supports it
- It's a good first step in supporting multiple translations in Medusa

**How**

Using `i18next`.

**Testing**

### CODE REVIEW

**Comment by mj-mehdizadeh** [comment]
Thank you @gempain , if you need me to do anything, I like to help.

**Comment by gempain** [comment]
@mj-mehdizadeh if you could tell / show me how you were able to run the local development... I tried [what the docs say](https://docs.medusajs.com/development/fundamentals/local-development#run-tests-in-the-repository) but that didn't help much to be honest. I then read what was behind the `develop` command and that helped me start the dev server (which fails to restart when a file changes in the `packages/medusa` directory... 

Starting the admin-ui app is simple, but I haven't yet succeeded in having it communicate with the dev server. I have weird errors in my Chrome console even though I see in the vite config they have configured it to target `localhost:9000`.

Totally interested in a call through Google Meets or Slack if you're interested. Any way to get in touch other than publicly here on Gh ?

The first thing I want to do is add keys to all `t(...)`:

```
t('Hello') -> t('my.key.hello')
```

This enhances stability so that when someone changes an English translation, they do it in the JSON file instead of in the ui and it doesn't break the reference of other translation files.

**Comment by samuelstroschein** [comment]
Let us (https://github.com/inlang/inlang) know if we can help with expertise or dev tools for example

**Comment by gempain** [comment]
TODO:
- [ ] shorten long keys
- [ ] handle occurrences where no key was yet generated

**Pull request closed without merging**
